### ISSUE TITLE
Good one

### ISSUE THREAD

**Issue by KrishnaPG** [jagi/meteor-reactive-map#2]
This is a good one. Better than the half-baked reactiveDict from the core, at least.

One small suggestion though. Please highlight in the readme.md that this is reactive at the `container level` as well at the `element level`. (Am I right in my understading that this package allows to track changes to individual objects in the map also right?)

Also, small issue at https://github.com/jagi/meteor-reactive-map/blob/master/lib/reactive_map.js#L39-L41

```
  this._keysDeps = new Tracker.Dependency;
  this._valuesDeps = new Tracker.Dependency;
  this._keyDeps = {}; 
```

Looks like `this._keyDeps` is being initialized twice in two lines differently. Was that intentional?

**Comment by lukejagodzinski** [comment]
Thanks :). I had to create it because built in ReactiveDict is condemned and I needed something more functional for my [Astronomy](https://atmospherejs.com/jagi/astronomy) library. Take a look at it also. It may interest you if you are currently using simple schema.

If it goes about reactivity. It's reactive in two ways. It tracks number of elements and individual element's values and their existence. So you may say that it's reactive on the level of container and on the level of element. However I think it's quite obvious after taking a look at methods list. Maybe I will add information that every method is reactive.

No, it's not an error. Notice that one variable is named `_keysDeps` and another one `_keyDeps`. They are responsible for different things.

**Comment by KrishnaPG** [comment]
Thanks. Didn't realize the 's' in the keys vs key

As for reactivity - yes there are few reactive containers out there (such as reactivearray package) which are reactive at container level rather than at the element level.
