### ISSUE TITLE
Serialization necessary?

### ISSUE THREAD

**Issue by dalgard** [jagi/meteor-reactive-map#4]
I turned to this package, because `ReactiveDict` serializes its values. It does this, because it has the feature of restoring the values after a hot code push.

Does `ReactiveMap` have a similar feature that makes it necessary to use EJSON for values?

I'd like to be able to store and retrieve objects with methods on them. `ReactiveMap` is very useful to me, because every call to `get` registers a dependency, even if a value hasn't been set yet.

**Comment by lukejagodzinski** [comment]
Hi, yes it serializes values and to be honest I just made it because I was inspired by ReactiveDict. I don't know how would it behave without serialization. I would need to make tests. However, storing references to objects in ReactiveMap is not a good thing in my opinion. Because changing original object, you would also change object stored in the ReactiveMap and reactivity would not take place.

**Comment by dalgard** [comment]
It's good to protect developers, but I think the principle about passing things by reference vs. by value is a fair level to place the bar at. In other words, I think developers should be trusted to administrate this small gotcha.

I can say with confidence, that it wouldn't behave any different – one would simply be able to use objects with methods as values in the map.

Please consider it.

**Comment by lukejagodzinski** [comment]
I will make tests and decide if it will work with Astronomy after releasing 1.0.0

**Comment by dalgard** [comment]
That's all I'd ask for – thanks :)

**Comment by lukejagodzinski** [comment]
Sorry that it took so long but after tests I've decided to release 2.0 version that does not serialize values. It has also some changes about which you can read in the README.

**Comment by dalgard** [comment]
Interesting – I released my own version a few days ago, which is an exact copy of ReactiveDict without the JSON and written in ES15 :)

https://github.com/dalgard/meteor-reactive-map

Thanks, though. Maybe I'll deprecate my package again, when I find time to look at `jagi:reactive-map` 2.0.

**Comment by dalgard** [comment]
I don't see any specific stuff in the readme about 2.0?

On another note, I don't think it's right comparing this package to the native `Map` in ES2015 – the point of `Map` is to allow the use of any object as a key. This is not something that can be shimmed.

**Comment by lukejagodzinski** [comment]
I've just allowed to initialize the Map with values at construction. There it's a change in how the `entries` method work - now it works the same way as original method in Map. The `all` method is not present in JavaScript Map object, however here it's used to take all key-value pairs. And of course there is no serialization right now. There are also some minor fixes to returned values.

Hmm objects as keys... Maybe it could be possible to shim. I would have to think about it. Maybe it'snot the best to call it the reactive implementation of ES2015 Map. However I decided to call it Map because it has similar API.

**Comment by dalgard** [comment]
I understand the motivation around adhering to the API of ES6 `Map`. But the reasons for adding `Map` as a native type and the failed attempts to polyfill it is sort of a theme within that whole domain, and for that reason, I think it's misleading to claim that `jagi:reactive-map` does so.

https://github.com/eriwen/es6-map-shim (deprecated)

**Comment by lukejagodzinski** [comment]
When creating ReactiveMap 2.0 I was thinking about using the Map object internally to store values. Thanks to that I would create almost 1 to 1 implementation with reactivity. But after research I've realized that support for Map especially in IE is very bad.

If it goes about Map shim. It definitely not possible to shim all the features in all old browsers. But when talking about ReactiveMap, I mean more something like Map like experience.

Summing everything up, I think that I will remove information that it's reactive map implementation. It will cause less confusion.

**Comment by dalgard** [comment]
That's cool. Thanks for your work :+1:
